6. Write a program to add a border of zeros around the existing array.
For example,
If you have the below array:

[[ 1.  1.  1.  1.]                                                          
 [ 1.  1.  1.  1.]                                                          
 [ 1.  1.  1.  1.]] 
The resultant array should be: (zeros on the border and 1s within it)

[[ 0.  0.  0.  0.  0.  0.]                                                  
 [ 0.  1.  1.  1.  1.  0.]                                                  
 [ 0.  1.  1.  1.  1.  0.]                                                  
 [ 0.  1.  1.  1.  1.  0.]                                                  
 [ 0.  0.  0.  0.  0.  0.]]

In [2]:
import numpy as np

# Create NumPy arrays filled with ones
ones_arr = np.ones((4,4))

print("Transformed array:")
transformed_array = np.pad(ones_arr, pad_width=1, mode='constant', constant_values=0)
print(transformed_array)

Transformed array:
[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


np.ones(shape, dtype=None, order='C') --> it returns a new array of given shape and data type, where element's value is set to 1.

np.pad(array, pad_width, mode, **kwargs) -->when there is a need to perform padding in NumPy arrays, numpy.pad() function is used