8. Write a program for interchanging two axes of the NumPy array.

In [3]:
import numpy as np

arr = np.array([[1,2,3]])
print("Original array: ")
print(arr)

#Swap axes
axis_swapped_arr =  np.swapaxes(arr,0,1)
print("Transformed array: ")
print(axis_swapped_arr)

Original array: 
[[1 2 3]]
Transformed array: 
[[1]
 [2]
 [3]]


np.swapaxes(arr, axis1, axis2) --> interchange two axes of an array


In [7]:
import numpy as np

arr = np.array([[[1,2], [3,4] ,[5,6]]])
print("Original array: ")
print(arr)

#Swap axes
axis_swapped_arr =  np.swapaxes(arr,0,2)
print("Transformed array: ")
print(axis_swapped_arr)

Original array: 
[[[1 2]
  [3 4]
  [5 6]]]
Transformed array: 
[[[1]
  [3]
  [5]]

 [[2]
  [4]
  [6]]]
