4. How can we convert DataFrame into a NumPy array?

In order to convert a dataframe into a NumPy array we use DataFrame.to_numpy() method.

Syntax:

DataFrame.to_numpy(dtype=None, copy=False, na_value=_NoDefault.no_default)

In [1]:
import pandas as pd

# initialize a dataframe
df = pd.DataFrame(
	[[10, 12, 33],
	[41, 53, 66],
	[17, 81, 19],
	[10, 11, 12]],
	columns=['X', 'Y', 'Z'])

# convert dataframe to numpy array
arr = df.to_numpy()

print('\nNumpy Array\n----------\n', arr)
print(type(arr))


Numpy Array
----------
 [[10 12 33]
 [41 53 66]
 [17 81 19]
 [10 11 12]]
<class 'numpy.ndarray'>
