Convert DataFrame to Numpy Array

Syntax:

DataFrame.to_numpy(dtype=None, copy=False, na_value=_NoDefault.no_default)

Parameters:

dtype: It accepts string or numpy.dtype. It is an optional parameter.

copy: It accepts a boolean value whose default is set to False.

na_value: It is an optional parameter. It specifies the value to use for missing values. The data type will depend on the data type of the column in the dataframe

In [1]:
import pandas as pd

# initialize a dataframe
df = pd.DataFrame(
	[[1, 2, 3],
	[4, 5, 6],
	[7, 8, 9],
	[10, 11, 12]],
	columns=['a', 'b', 'c'])

# convert dataframe to numpy array
arr = df.to_numpy()

print('\nNumpy Array\n----------\n', arr)
print(type(arr))


Numpy Array
----------
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
<class 'numpy.ndarray'>


In [2]:
import pandas as pd

# initialize a dataframe
df = pd.DataFrame(
	[[1, 2, 3],
	[4, 5, 6],
	[7, 8, 9],
	[10, 11, 12]],
	columns=['a', 'b', 'c'])

# convert dataframe to numpy array
arr = df[['a', 'c']].to_numpy()

print('\nNumpy Array\n----------\n', arr)
print(type(arr))


Numpy Array
----------
 [[ 1  3]
 [ 4  6]
 [ 7  9]
 [10 12]]
<class 'numpy.ndarray'>
