ONE-DIMENSIONAL ARRAY

In [1]:
import numpy as np
 
arr = [1,2,3,4]        #python list
numpy_arr = np.array(arr)    #numpy array
print (numpy_arr)

#using np.array() function, we can create NumPy arrays of any dimensions 

[1 2 3 4]


TWO-DIMENSIONAL ARRAY

In [2]:
import numpy as np

arr = [[1,2,3,4], [5,6,7,8]]
numpy_arr = np.array(arr)
print(numpy_arr)

#using np.array() function, we can create NumPy arrays of any dimensions 

[[1 2 3 4]
 [5 6 7 8]]


THREE-DIMENSIONAL ARRAY

In [4]:
import numpy as np

arr = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
numpy_arr = np.array(arr)
print(numpy_arr)

#using np.array() function, we can create NumPy arrays of any dimensions 

[[1 2 3]
 [4 5 6]
 [7 8 9]]
