Concatenate 2 arrays

Syntax: np.concatenate((a1, a2, ...), axis=0, out=None) 
where, 
a1,a2: arrays of the same shape
axis: Represents the axis along which the arrays are joined. The default value is 0.
out: If mentioned, it specifies the destination for placing the result.

In [2]:
import numpy as np
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

# Concatenate with axis 0
c = np.concatenate((a,b), axis=0)
print("With axis 0: \n",c )

# Concatenate with axis 1 (b.T represents transpose matrix)
d = np.concatenate((a,b.T), axis=1)
print("With axis 1: \n",d )


With axis 0: 
 [[1 2]
 [3 4]
 [5 6]]
With axis 1: 
 [[1 2 5]
 [3 4 6]]
