Both  vstack() and hStack() methods are used for combining the NumPy arrays.
The main difference is that the hstack method combines arrays horizontally whereas the vstack method combines arrays vertically.

In [1]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])

# vstack arrays
c = np.vstack((a,b))
print("After vstack: \n",c)
# hstack arrays
d = np.hstack((a,b))
print("After hstack: \n",d)

After vstack: 
 [[1 2 3]
 [4 5 6]]
After hstack: 
 [1 2 3 4 5 6]
