fliplr() method, used to flip an array from left or right direction. The columns are preserved but the order of elements in the columns would be different than before

Syntax: np.fliplr(arr)

In [3]:
import numpy as np 
  
array = np.arange(8).reshape((2,4)) 
print("Original array : \n", array) 
  
# fliplr : means flip left-right 
print("\nFlipped array left-right : \n", np.fliplr(array)) 

Original array : 
 [[0 1 2 3]
 [4 5 6 7]]

Flipped array left-right : 
 [[3 2 1 0]
 [7 6 5 4]]


flipud() method also flips the array but in the up or down direction. The rows are preserved in this case but they can appear in a different order in the result.

Syntax: np.flipud(arr)

In [5]:
import numpy as np 
  
array = np.arange(8).reshape((2,4)) 
print("Original array : \n", array) 
  
# flipud : means flip up-down 
print("\nFlipped array : \n", np.flipud(array)) 

Original array : 
 [[0 1 2 3]
 [4 5 6 7]]

Flipped array : 
 [[4 5 6 7]
 [0 1 2 3]]
