Multiplying 2 NumPy Array matrices

In [4]:
import numpy as np

# NumPy matrices
A = np.arange(15,24).reshape(3,3)
B = np.arange(20,29).reshape(3,3)
print("A: ",A)
print("B: ",B)

# Multiply A and B
result = A.dot(B)
#result1 = B.dot(A)
print("Result: ", result)


A:  [[15 16 17]
 [18 19 20]
 [21 22 23]]
B:  [[20 21 22]
 [23 24 25]
 [26 27 28]]
Result:  [[1110 1158 1206]
 [1317 1374 1431]
 [1524 1590 1656]]


np.arange() is used to return an array with evenly spaced elements as per the interval.

reshape() is udes to change shape of an array. The shape of an array is the number of elements in each dimension