np.split(), used to split the numpy array

Syntax: np.split(array, sections, axis=0)
where,
array - array that needs to be split
sections - If we give an integer X, X equal sub-arrays are obtained after dividing the array. If the split is not possible, ValueError is raised.

In [9]:
import numpy as np

a = np.arange(8)
split_arr = np.split(a, 2)
split_arr

[array([0, 1]), array([2, 3, 4, 5, 6, 7])]

In [11]:
import numpy as np

a = np.arange(6)
split_arr = np.split(a, [3])
split_arr

[array([0, 1, 2]), array([3, 4, 5])]

In [8]:
import numpy as np

a = np.arange(6.0)
split_arr = np.split(a, [3, 4, 5, 6, 7, 8]) 
split_arr

[array([0., 1., 2.]),
 array([3.]),
 array([4.]),
 array([5.]),
 array([], dtype=float64),
 array([], dtype=float64),
 array([], dtype=float64)]

#As the provided index exceeds the array dimension along the given axis, then an empty subarray will be returned.