Vectorization in NumPy

-Write your required function that takes array elements as parameters.
-Vectorize the function by making use of the vectorize() method of the NumPy package.
-Give array inputs to the vectorized function.

In [1]:
import numpy as np
# Define your function
def add(arr1, arr2):
    return (arr1 + arr2)

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

#vectorize add method
vectorized_add = np.vectorize(add)

#call vectorized method
result = vectorized_add(arr1, arr2)

print(result)

[5 7 9]


In [5]:
import numpy as np
# Define your function
def sub(arr1, arr2):
    return (arr1 - arr2)

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

#vectorize add method
vectorized_sub = np.vectorize(sub)

#call vectorized method
result = vectorized_sub(arr1, arr2)

print(result)

[-3 -3 -3]


In [6]:
import numpy as np
# Define your function
def mul(arr1, arr2):
    return (arr1 * arr2)

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

#vectorize add method
vectorized_mul = np.vectorize(mul)

#call vectorized method
result = vectorized_mul(arr1, arr2)

print(result)

[ 4 10 18]
